name: Build wheels

on: [push, pull_request, release]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        #, macos-latest]

    steps:
      - uses: actions/checkout@v5      
        with:
          submodules: recursive
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: latest
      - name: Configure compilers (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "CC=${{ steps.setup-fortran.outputs.cc }}" >> $env:GITHUB_ENV
          echo "CXX=${{ steps.setup-fortran.outputs.cxx }}" >> $env:GITHUB_ENV
          echo "FC=${{ steps.setup-fortran.outputs.fc }}" >> $env:GITHUB_ENV
      - uses: pypa/cibuildwheel@v3.2.0
        with:
          package-dir: .
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
    env:
      CIBW_ARCHS_MACOS: "universal2"
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
