name: Build wheels

on: [push, pull_request, release]

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v5      
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: latest
      - uses: pypa/cibuildwheel@v3.2.0
        with:
          package-dir: .
    env:
      CIBW_ARCHS_MACOS: "x86_64 arm64 universal2"
      CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"
      CIBW_TEST_COMMAND: "python -c 'import myproject; print(myproject.__doc__)'"
